# -----------------------------
# SQLite database connection
# -----------------------------
spring.datasource.url=jdbc:sqlite:/data/myapp.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# -----------------------------
# Redis configuration
# -----------------------------
spring.data.redis.host=redis
spring.data.redis.port=6379
# -----------------------------
# Web server
# -----------------------------
server.address=0.0.0.0
server.port=8080

# -----------------------------
# Logging
# -----------------------------
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.kafka=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.jdbc.datasource.init=DEBUG